# Generated by Django 5.0.6 on 2024-07-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
