# Generated by Django 5.0.6 on 2024-07-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign',
        ),
    ]
