# Generated by Django 5.0.6 on 2024-07-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
